export default {
  HOST_OPENED: 'HOST_OPENED',
  HOST_NAME_CHANGE: 'HOST_NAME_CHANGE',
  CONNECTION_OPENED: 'CONNECTION_OPENED',
  DATA_RECEIVED: 'DATA_RECEIVED',
  STREAM_RECEIVED: 'STREAM_RECEIVED',
};
